---
- name: Get List of PVE Roles in JSON format
  shell: "pveum role list --output-format=json | jq 'map(select(.roleid == \"{{item.name}}\"))'"
  register: pve_role
- name: Add Packer PVE Role if it does not exist.
  command:
    argv:
      - pveum
      - role
      - add
      - "{{item.name}}"
      - -privs 
      - "{{item.privs | join(' ')}}"
  when: pve_role == '[]'
- name: Modify Packer PVE Role if privs not equal
  command:
    argv:
      - pveum
      - role
      - modify
      - "{{item.name}}"
      - -privs 
      - "{{item.privs | join(' ')}}"
  when: (pve_role.stdout | from_json)[0].privs != (item.privs | sort | join(','))