---
- name: Get List of PVE Users in JSON Format
  shell: "pveum user list --output-format=json | jq 'map(select(.userid == \"{{item.name}}@{{item.realm}}\"))'"
  register: pve_user

- name: Add User if it does not exist
  command:
    argv:
      - pveum
      - user
      - add
      - "{{item.name}}@{{item.realm}}"
  when: pve_user.stdout == "[]"