---
# tasks file for proxmox

- name: Download local binaries
  get_url:
    checksum: "{{ item.checksum }}"
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - url: https://github.com/stedolan/jq/releases/download/jq-{{versions.jq.version}}/jq-linux64
      checksum: "{{ versions.jq.checksum }}"
      dest: "/usr/bin/jq"
      mode: u+x

- name: Install non-enterprise apt source
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    line: deb http://download.proxmox.com/debian buster pve-no-subscription
    state: present

- name: Remove enterprise apt repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: ^deb https\://enterprise\.proxmox\.com/debian/pve buster pve-enterprise$
    replace: "#deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Add PVE Roles
  block:
    - name: Get List of PVE Roles in JSON format
      command: "pveum role list --output-format=json | jq 'map(select(.roleid == \"{{item.name}}\")) | length == 0'"
      register: pve_role_does_not_exist
    - name: Add Packer PVE Role if it does not exist.
      command: "pve role add {{item.name}} -privs \"{{item.privs | join(' ')}}\""
      when: pve_role_does_not_exist
  loop:
    - name: Packer
      privs:
        - VM.Config.Disk
        - VM.Config.CPU
        - VM.Config.Memory
        - Datastore.AllocateSpace
        - Sys.Modify
        - VM.Config.Options
        - VM.Allocate
        - VM.Audit
        - VM.Console
        - VM.Config.CDROM
        - VM.Config.Network
        - VM.PowerMgmt
        - VM.Config.HWType
        - VM.Monitor