---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian8-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
